### ISSUE TITLE
有關綁定密碼疑問

### ISSUE THREAD

**Issue by geek01** [tad0616/tad_login#9]
感覺是為了自動登入$xoopsAuth->authenticate($uname, $pass);
的$pass密碼，特地做了可逆加密措施並且寫入另一個表做查照
是不是直接在綁定密碼時，直接就用password_hash加密寫入users表
登入時，用$uname查出密碼後用password_verify比對正確性就好
用md5加密寫入users表後，用xoops登入方式還是會被改寫掉
現有的作法，會一直取出密碼再用md5寫入然後再被hash寫入
以上感想，不知我有沒有思考不周的地方

**Comment by tad0616** [comment]
其實跟OpenID取得的資料大概只有姓名跟Email，不會有密碼，所以得自己生個密碼
早期的密碼是隨機產生128位元的密碼並用明碼存到tad_login_random_pass中，並用他當作 XOOPS 使用者密碼。
也就是說，只要能取得tad_login_random_pass的內容，就能以任何人身份登入。

最近得知桃園市即將取消OpenID服務，所以許多學校擔心既有的OpenID無法延續使用
所以，才做了綁定密碼，也就是讓登入者可以修改自己在tad_login_random_pass中的密碼
日後即使OpenID無法使用，也可以用XOOPS登入方式來使用同一個帳號
正因為可以修改密碼，所以，才把tad_login_random_pass中的密碼也加密
但同時又要讓系統可以解密，如此才能自動登入$xoopsAuth->authenticate($uname, $pass);

之所以還是用md5()而不是用password_hash()是因為還有許多學校仍在用PHP5...
僅為了提高相容性而不得已的作法

**Comment by geek01** [comment]
原來是這樣呀
辛苦tad大了～
